name: shartflix
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # âš™ï¸ CORE & ARCHITECTURE
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  go_router: ^16.0.0
  equatable: ^2.0.7

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # ğŸŒ ENVIRONMENT & CONFIGURATION
  flutter_dotenv: ^5.2.1

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # ğŸŒ LOCALIZATION & LANGUAGE
  easy_localization: ^3.0.0

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # ğŸ’¾ STORAGE & CACHE
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # ğŸ“· MEDIA & PERMISSIONS
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  path: ^1.9.1

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # ğŸ§° UTILITIES
  validators: ^3.0.0
  loader_overlay: ^5.0.0
  custom_refresh_indicator: ^4.0.1

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # ğŸ§ª DEBUGGING & LOGGING
  logger: ^2.4.0

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # â˜ï¸ FIREBASE
  firebase_core: ^2.30.0
  firebase_crashlytics: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/release.env
    - assets/lang/
    - assets/icons/
